name: Multi-Platform Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Ellenőrizd ki a forrástárat
    - uses: actions/checkout@v4

    # Állítsd be a Docker Buildx-et
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2


    # Építsd meg a képet több platformra
    - name: Build and Push Multi-Platform Docker Image
      uses: docker/build-push-action@v5
      with:
        push: false
        tags: |
          my-image-name:latest
          my-image-name:${{ github.sha }}
        platforms: linux/amd64,linux/arm/v7
